apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: gemma-2b-vllm-inference-server
  name: gemma-2b-vllm-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: vllm-token-latency-ms
      target:
        type: AverageValue
        averageValue: 50
