apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: singlehost-inference-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: singlehost-inference-deployment-blueprint
  # TODO: also include stabilizing-windows, tolerance threshold, etc.
